# Generated by Django 5.0.6 on 2024-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0002_producto2_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen_nombre',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
