# Generated by Django 5.0.6 on 2024-07-02 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0003_alter_imagen_imagen_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen_nombre',
            field=models.ImageField(upload_to='productos/imagenes/'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appbebitus.producto2'),
        ),
    ]
