# Generated by Django 5.0.6 on 2024-07-02 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto2',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_marca', models.CharField(max_length=100)),
                ('producto_talla', models.CharField(max_length=50)),
                ('producto_jaba_paquetes', models.IntegerField()),
                ('producto_jaba_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_paquete_unidad', models.IntegerField()),
                ('producto_paquete_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_nombre', models.ImageField(upload_to='productos/imagenes/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appbebitus.producto')),
            ],
        ),
    ]
