# Generated by Django 5.0.6 on 2024-07-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0004_alter_imagen_imagen_nombre_alter_imagen_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_detalle',
            new_name='prod_detalle',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_id',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_jaba_paquetes',
            new_name='prod_jaba_n_paquetes',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_jaba_precio',
            new_name='prod_jaba_precio',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_marca',
            new_name='prod_marca',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_paquete_unidad',
            new_name='prod_paquete_n_unidad',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_paquete_precio',
            new_name='prod_paquete_precio',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='producto_talla',
            new_name='prod_talla',
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_peso_fin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_peso_ini',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_tiempo_absorcion',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
