# Generated by Django 5.0.6 on 2024-07-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0005_rename_producto_detalle_producto2_prod_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_jaba_n_paquetes',
            new_name='prod_jaba_paquetes',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_paquete_n_unidad',
            new_name='prod_paquete_unidad',
        ),
    ]
