# Generated by Django 5.0.6 on 2024-07-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0006_rename_prod_jaba_n_paquetes_producto2_prod_jaba_paquetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto2',
            name='prod_peso_fin',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto2',
            name='prod_peso_ini',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
