# Generated by Django 5.0.6 on 2024-07-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0007_alter_producto2_prod_peso_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto2',
            name='prod_tiempo_absorcion',
            field=models.IntegerField(),
        ),
    ]
