# Generated by Django 5.0.6 on 2024-07-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0008_alter_producto2_prod_tiempo_absorcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto2',
            name='prod_jaba_precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto2',
            name='prod_paquete_precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
