# Generated by Django 5.0.6 on 2024-07-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbebitus', '0009_alter_producto2_prod_jaba_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_detalle',
            new_name='prod_descripcion',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_jaba_paquetes',
            new_name='prod_jaba_paquete',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_peso_ini',
            new_name='prod_jaba_peso',
        ),
        migrations.RenameField(
            model_name='producto2',
            old_name='prod_tiempo_absorcion',
            new_name='prod_tiempo_proteccion',
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_color',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_paquete_medida',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_paquete_peso',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto2',
            name='prod_peso_inicio',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
